name: Example GPU CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'ci/**'
      - '.github/workflows/containers.yml'
  pull_request:
    paths-ignore:
      - 'ci/**'
      - '.github/workflows/containers.yml'

permissions:
  contents: read
  packages: read

env:
  WHEEL_TAG: manylinux_2_28_x86_64

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-wheels:
    name: Build wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6

      - name: Log in to the Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: "ghcr.io/gpu-ci-demo/manylinux_2_28_x86_64_12_9:latest"
          CIBW_BUILD: "cp312-manylinux_x86_64"

      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: wheels_windows_x86_64__${{ github.sha }}
          path: ./wheelhouse/*.whl
