name: Example GPU CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'ci/**'
      - '.github/workflows/containers.yml'
  pull_request:
    paths-ignore:
      - 'ci/**'
      - '.github/workflows/containers.yml'

permissions:
  contents: read
  packages: read

defaults:
  run:
    shell: bash -el {0}

jobs:
  build-wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        manylinux-base: [manylinux_2_28, manylinux_2_34]
        cuda-version: [12_9, 13_1]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: actions/setup-python@v6

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: >-
            quay.io/manylinux_cuda/${{ matrix.manylinux-base }}_x86_64_cuda${{ matrix.cuda-version }}:latest
          CIBW_BUILD: cp312-manylinux_x86_64

      - name: Upload wheels
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: python-wheel-${{ matrix.manylinux-base }}-cuda${{ matrix.cuda-version }}
          path: ./wheelhouse/*.whl

  test-wheel:
    name: Test wheel
    needs: build-wheels
    runs-on:
      group: cuda-gpu-runner-group
    container:
      # Use a modified version of nvidia/cuda container
      image: ghcr.io/gpu-ci-demo/example_gpu_ci:cuda_test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: "--gpus all"
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: python-wheel-manylinux_2_34-cuda13_1
      - name: Run pytests
        run: |
          source activate gpu_test
          python --version
          python -m pip install ./example-*.whl
          python -m pytest -v tests/
